disabled_rules:
  - cyclomatic_complexity
  - blanket_disable_command
  - block_based_kvo
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - line_length
  - nesting
  - syntactic_sugar
  - trailing_comma
  - trailing_whitespace
  - type_body_length
  - vertical_whitespace
  - unavailable_condition
reporter: "xcode"
