name: CI

on:
  push:
    branches: 
      - master
      - hakburi/*
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - name: Action Runner Info
        run: |
          echo "$(whoami)@$(scutil --get ComputerName)"
  
