name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-11
    timeout-minutes: 120
    steps:
      - name: Action Runner Info
        run: |
          echo "$(whoami)@$(scutil --get ComputerName)"
          echo "OS Version: $(sw_vers -productVersion)"
          #echo "Ruby(rbenv): $(rbenv global)"
          echo "Ruby: $(ruby --version)"
          echo "$(bundle --version)"
          echo "Carthage: $(carthage version)"
          #echo "Carthage/Rome: $(rome --version)"
          echo "Tuist: $(tuist version)"

      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install tuist
        run: | 
            bash <(curl -Ls https://install.tuist.io)
            
      - name: Package Info
        run: |
          echo "Ruby: $(ruby --version)"
          echo "$(bundle --version)"
          echo "Tuist: $(tuist version)"
          
      - uses: tuist/tuist-action@0.13.0
        with: 
          command: 'build'
          arguments: ''
          
      - name: Testing
        run: | 
            xcodebuild test \
            -project GithubSearch.xcodeproj \
            -scheme UnitTests \
            -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=15.2"
