name: CI

on:
  push:
    branches: 
      - master
      - hakburi/*
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-11
    timeout-minutes: 120
    steps:
      - name: Action Runner Info
        run: |
          echo "$(whoami)@$(scutil --get ComputerName)"
          echo "OS Version: $(sw_vers -productVersion)"
          #echo "Ruby(rbenv): $(rbenv global)"
          echo "Ruby: $(ruby --version)"
          echo "$(bundle --version)"
          echo "Carthage: $(carthage version)"
          #echo "Carthage/Rome: $(rome --version)"
          echo "Tuist: $(tuist version)"

      - name: Cache Ruby Dependencies
      - uses: action/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
          
